/*
Anandi and Jagya were getting married again when they have achieved proper age. Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. But he can give only one blessing of K length because some priest told him to do so. Thus he decides to generate a blessing using the other two blessings. While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.
The generated blessing is a common subsequence of length K of the two blessings he has. Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum. If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has.
Input Specification
First line consists of number of test cases t. Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.
Output Specification
Output consists of t lines each containing an integer denoting the maximum happiness value that can be generated by the two blessings.
Constraint
1 <= t <= 50

1 <= length(b1) , length(b2) <= 100 

1 <= K <= 100
Sample Input
2
asdf
asdf
3
anandi
jagya
3
Sample Output
317
0
*/

#include <bits/stdc++.h>
using namespace std;
int helper(string s1,string s2,int m,int n,int k,int ***dp)
{
    int option1=-1;
    if(k==0)
        return 0;
    if(m==-1 || n==-1)
        return -1;
    if(dp[m][n][k]!=-2)
        return dp[m][n][k];
    if(m-1>=0 && n-1>=0 && s1[m-1]==s2[n-1])
    {
        option1=helper(s1,s2,m-1,n-1,k-1,dp);
        if(option1!=-1)
            option1+=s1[m-1];
    }
    int option2=-1;
    int option3=-1;
    option2=helper(s1,s2,m-1,n,k,dp);
    option3=helper(s1,s2,m,n-1,k,dp);
    dp[m][n][k]=max(option1,max(option2,option3));
    return dp[m][n][k];
    
}

int max_blessing(string s1,string s2,int k)
{
    int m=s1.length();
    int n=s2.length();
    if(m<k || n<k)
        return 0;
    int ***dp=new int **[m+1];
    for(int i=0;i<m+1;i++)
    {
        dp[i]=new int *[n+1];
        for(int j=0;j<n+1;j++)
        {
            dp[i][j]=new int[k+1];
        }
    }
    for(int i=0;i<m+1;i++)
        for(int j=0;j<n+1;j++)
            for(int l=0;l<k+1;l++)
                dp[i][j][l]=-2;
    int ans=helper(s1,s2,m,n,k,dp);
    if(ans==-1)
        ans=0;
    for(int i=0;i<m+1;i++)
    {
        for(int j=0;j<n+1;j++)
        {
            delete [] dp[i][j];
        }
        //delete [] dp[i];
    }
    delete [] dp;
    return ans;
}

int main()
{
    int t;
    cin>>t;
    while(t--)
    {
        string b1,b2;
        int k;
        cin>>b1;
        cin>>b2;
        cin>>k;
        cout<<max_blessing(b1,b2,k)<<endl;
    }
    return 0;
}
